name: Task Sync Every 15 Minutes
on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes
  workflow_dispatch:
env:
  TZ: 'America/New_York'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -e .

      - name: Run script
        env:
          PYTHONPATH: ${{ github.workspace }}
          PYTHONIOENCODING: utf-8  # Add this line
          LANG: C.UTF-8            # Add this line
          LC_ALL: C.UTF-8          # Add this line
          # Add Python debugging flags
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DAILY_TRACKING_DB_ID: ${{ secrets.NOTION_DAILY_TRACKING_DB_ID }}
          NOTION_PILLAR_DB_ID: ${{ secrets.NOTION_PILLAR_DB_ID }}
          NOTION_WEEK_DB_ID: ${{ secrets.NOTION_WEEK_DB_ID }}
          NOTION_MONTH_DB_ID: ${{ secrets.NOTION_MONTH_DB_ID }}
          NOTION_QUARTER_DB_ID: ${{ secrets.NOTION_QUARTER_DB_ID }}
          NOTION_PROJECT_DB_ID: ${{ secrets.NOTION_PROJECT_DB_ID }}
          NOTION_TASKS_DB_ID: ${{ secrets.NOTION_TASKS_DB_ID }}
          NOTION_GOAL_DB_ID: ${{ secrets.NOTION_GOAL_DB_ID }}
          NOTION_SUBCATEGORY_DB_ID: ${{ secrets.NOTION_SUBCATEGORY_DB_ID }}
          AM_API_TOKEN: ${{ secrets.AM_API_TOKEN }}
          AM_FULL_ACCESS_TOKEN: ${{ secrets.AM_FULL_ACCESS_TOKEN }}
          AM_SYNC_SERVER: ${{ secrets.AM_SYNC_SERVER }}
          AM_SYNC_DATABASE: ${{ secrets.AM_SYNC_DATABASE }}
          AM_SYNC_USER: ${{ secrets.AM_SYNC_USER }}
          AM_SYNC_PASSWORD: ${{ secrets.AM_SYNC_PASSWORD }}
          TZ: 'America/New_York'
        run: |
          python pipelines/every_fifteen_minutes.py