name: Task Counting Workflow
on:
  repository_dispatch:
    types: [count-tasks]
  workflow_dispatch:
    inputs:
      name:
        description: "DawnMarie"
        required: true
        default: "warning"
        
env:
  TZ: 'America/New_York'

jobs:
  count-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -e .

      - name: Run task counting script
        env:
          PYTHONPATH: ${{ github.workspace }}
          PYTHONIOENCODING: utf-8
          LANG: C.UTF-8
          LC_ALL: C.UTF-8
          PYTHONUTF8: 1
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_TASKS_DB_ID: ${{ secrets.NOTION_TASKS_DB_ID }}
          EXIST_TOKEN: ${{ secrets.EXIST_TOKEN }}
          TZ: 'America/New_York'
        run: |
          python pipelines/task_counting.py
